{% set name = "vaex" %}
{% set version = "4.11.1" %}
{% set sha256 = "6a5da199e8615a799bd9425f459529218ca4dcae150bbb3a5b2a6dd22c06d482" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - vaex-core <4.12.0,>=4.11.1
    - vaex-astro <0.10,>=0.9.1
    - vaex-hdf5 <0.13,>=0.12.3
    - vaex-viz <0.6,>=0.5.2
    - vaex-server <0.9,>=0.8.1
    - vaex-jupyter <0.9,>=0.8.0
    - vaex-ml <0.19,>=0.18.0
    # - vaex-distributed
    # - vaex-ui
    # - vaex-graphql

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  dev_url: https://github.com/vaexio/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  license_url: https://github.com/vaexio/vaex/tree/master/licenses
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  description: "Vaex is a high performance Python library for lazy Out-of-Core DataFrames (similar to Pandas), to visualize and explore big tabular datasets."
  doc_url: https://vaex.io/docs
  doc_source_url: https://github.com/vaexio/vaex/tree/master/docs

extra:
  skip-lints:
    - avoid_noarch
    - missing_pip_check

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/26940
    recipe-maintainers:
      - bkreider

  recipe-maintainers:
    - maartenbreddels
