{% set name = "vaex" %}
{% set version = "4.6.0" %}
{% set sha256 = "7988c9d323c1673b7a54e62170f66a761e5c4fd322c6ad9d72a68d44aab442ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - vaex-core <4.7,>=4.6.0
    - vaex-astro <0.9,>=0.8.3
    - vaex-hdf5 <0.12,>=0.11.0
    - vaex-viz <0.6,>=0.5.0
    - vaex-server <0.8,>=0.7
    - vaex-jupyter <0.7,>=0.6.0
    - vaex-ml <0.16,>=0.15.0
    # - vaex-distributed
    # - vaex-ui
    # - vaex-graphql

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://vaex.io/docs

extra:
  recipe-maintainers:
    - maartenbreddels
