{% set name = "vaex" %}
{% set version = "4.9.0" %}
{% set sha256 = "c1d3dfefd4d2d5a7c2750a3ff15cbb07d19a7fa1a28e706f6c156c10e5941803" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - vaex-core <4.10,>=4.9.2
    - vaex-astro <0.10,>=0.9.1
    - vaex-hdf5 <0.13,>=0.12.2
    - vaex-viz <0.6,>=0.5.2
    - vaex-server <0.9,>=0.8.1
    - vaex-jupyter <0.9,>=0.9.0
    - vaex-ml <0.18,>=0.17.0
    # - vaex-distributed
    # - vaex-ui
    # - vaex-graphql

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://vaex.io/docs

extra:
  recipe-maintainers:
    - maartenbreddels
