{% set name = "vaex" %}
{% set version = "3.0.0" %}
{% set sha256 = "e0914d419ef7c90e619b77d7bdff1cad88fddc575f83bd883b346291980a60f5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python
    - vaex-arrow <0.6,>=0.5.0
    - vaex-astro <0.8,>=0.7.0
    - vaex-core <3,>=2.0.0
    - vaex-hdf5 <0.7,>=0.6.0
    - vaex-jupyter <0.6,>=0.5.0
    - vaex-ml <0.10,>=0.9.0
    - vaex-server <0.4,>=0.3.0
    - vaex-viz <0.5,>=0.4.0
    # - vaex-distributed
    # - vaex-ui
    # - vaex-graphql

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://docs.vaex.io

extra:
  recipe-maintainers:
    - maartenbreddels
