{% set name = "vaex" %}
{% set version = "4.4.0" %}
{% set sha256 = "4f6c9726a2aa00ceaa14894ee5916bdb131c5f311786e8fe50f7cfe943aefc65" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - vaex-astro <0.9,>=0.8.3
    - vaex-core <5,>=4.4.0
    - vaex-hdf5 <0.10,>=0.9.0
    - vaex-jupyter <0.7,>=0.6.0
    - vaex-ml <0.14,>=0.13.0
    - vaex-server <0.7,>=0.6.0
    - vaex-viz <0.6,>=0.5.0
    # - vaex-distributed
    # - vaex-ui
    # - vaex-graphql

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://vaex.io/docs

extra:
  recipe-maintainers:
    - maartenbreddels
