{% set name = "vaex" %}
{% set version = "4.7.0" %}
{% set sha256 = "9ea36d8f3bef2bd33d8fc433c36c52fe133e2169c1def86e91c5a8c20b28a1e3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - vaex-core <4.8,>=4.7.0
    - vaex-astro <0.10,>=0.9.0
    - vaex-hdf5 <0.12,>=0.11.1
    - vaex-viz <0.6,>=0.5.1
    - vaex-server <0.9,>=0.8
    - vaex-jupyter <0.8,>=0.7.0
    - vaex-ml <0.17,>=0.16.0
    # - vaex-distributed
    # - vaex-ui
    # - vaex-graphql

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://vaex.io/docs

extra:
  recipe-maintainers:
    - maartenbreddels
