{% set name = "vaex" %}
{% set version = "2.3.0" %}
{% set sha256 = "2fd74d62cad4e809b505a675c478bce971c2585c0c454dcc43c4a2fce6b2c26c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 1
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=1.2.0,<2
    - vaex-viz >=0.3.8,<0.4
    - vaex-server >=0.2.1,<0.3
    - vaex-hdf5 >=0.5.5,<0.6
    - vaex-astro >=0.6.1,<0.7
    - vaex-arrow >=0.4.1,<0.5
    # - vaex-distributed
    # - vaex-jupyter
    # - vaex-ui

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://docs.vaex.io

extra:
  recipe-maintainers:
    - maartenbreddels
