{% set name = "vaex" %}
{% set version = "2.5.0" %}
{% set sha256 = "7992cbd6241f60b7f984ad20d672f5770d50b1700946878f09e28e96bb086214" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=1.2.0,<2
    - vaex-viz >=0.3.8,<0.4
    - vaex-server >=0.2.1,<0.3
    - vaex-hdf5 >=0.5.6,<0.6
    - vaex-astro >=0.6.1,<0.7
    - vaex-arrow >=0.4.1,<0.5
    - vaex-jupyter >=0.4.1,<0.5
    - vaex-ml >=0.6.2,<0.7
    # - vaex-distributed
    # - vaex-ui
    # - vaex-graphql

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://docs.vaex.io

extra:
  recipe-maintainers:
    - maartenbreddels
